---
title: "Example article on how to use templates"
author: "Frank Loesche"
institute: "Plymouth University"
date: "7 February 2017"
abstract:
  This example uses apa.template and actually puts some meta-data and variables from the markdown file into the template. The same template can therefore be used across different publications, but the template is slightly more difficult to generate. Have a look at apa-simple.template for a much simpler example.
keywords: 
- R
- RMarkdown
- APA
- LaTeX
- template
output:
  pdf_document:
    keep_tex: yes
    template: apa.template
    # template: "apa-simple.template"
bibliography: MyBibliography.bib
---

# Introduction

Citations go inside square brackets and are separated by semicolons. Each citation must have a key, composed of ‘@’ + the citation identifier from the database. For example, we have published a paper together [@Torre2016]. In another paper, which we cite in text, without parentheses, @Navon1977 talks about visual perception; and in another paper, for which we don't want to repeat the name of the author, he talks about psychology again [-@Navon1984]. This initial paragraph is followed by a number of meaningless lorem ipsum paragraphs. Please ignore.


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Two examples distributions"}
library(ggplot2)
set.seed(2820)

condition1 <- c(rnorm(100, mean = 2.7, sd = 1.4))
condition2 <- c(rnorm(100, mean = 4.5, sd = 1.8))

df <- data.frame(condition1, condition2)

ggplot(df) + 
  geom_density(aes(condition1), fill="red", alpha=.3)  + 
  geom_density(aes(condition2), fill="blue", alpha=.3) +
  labs(x="Questionnaire score", y="Frequency", title="Results from Questionnaire A") +
  xlim(0,7)
```

Saperet ocurreret mel te, nec audiam labitur scriptorem in, cu tantas impetus vel. Alia oratio vix at, cum at oporteat periculis ullamcorper. Mea dicunt mollis tacimates cu, eam ipsum iuvaret molestie ad. Ea mel quas insolens rationibus, pri ut diam erat detracto, ut nec facete denique maluisset. Ne usu unum perpetua.


Etiam doctus eu his, mea alia tota facilis eu, mucius adipisci consulatu ea pro. Pri ea sale salutandi repudiare, qui ea atqui facer accusam. Eu usu reque vocibus, id doctus facilisi imperdiet qui. Vix facete suscipit no.

# Another header

Veniam consectetuer ius ne, ex essent integre deseruisse qui. Eleifend definiebas reformidans mel no, debet scripserit nam ne. Vim cibo fabulas lobortis ei. Summo dicit eloquentiam mel ne, civibus quaerendum mea ei, appareat delicata forensibus te pro. In nisl ponderum antiopam sea. Mei ne maiorum praesent necessitatibus, nulla integre nam et.

## Second level header

Sea ignota iriure eu, fastidii appellantur usu et. Ut ius dicit eligendi interesset. An mei quod doctus assentior, in vim platonem oportere. Ea inani nostro fuisset usu. His ex alii novum munere, at graece inermis denique vis, saperet corpora eos at. Nulla deserunt qui an, at odio mentitum comprehensam pro.

- one element
- another one
- a third one

No duis epicuri usu, ex vel delenit erroribus. Vis id diam interesset eloquentiam. Eum te eruditi mandamus, ut vix recusabo adolescens. Adhuc maluisset deterruisset vix te, ex vis viris nostro explicari.


Vel id suas omnesque, nam errem persequeris te, quot recusabo appellantur ex vim. Nam ad esse viris sapientem. Qui id oportere periculis, quo amet persius atomorum ad. Eu adolescens voluptatibus delicatissimi mel, est modo lucilius ne. Nisl labores nonumes mel eu. Erant maiestatis democritum sed cu.

1. this is very important
2. this not so much
3. even less.

Eros magna vix at, possit invidunt vis id. Ad inani epicurei usu, simul quando te nec. Modo molestie voluptatum an has, vim et lorem iusto vocibus. Pro magna rebum ad, idque alterum consequuntur ut ius. Eu saperet omittam ponderum sit, qui volutpat maiestatis ut, timeam sanctus constituto sit ea.



Sea ignota iriure eu, fastidii appellantur usu et. Ut ius dicit eligendi interesset. An mei quod doctus assentior, in vim platonem oportere. Ea inani nostro fuisset usu. His ex alii novum munere, at graece inermis denique vis, saperet corpora eos at. Nulla deserunt qui an, at odio mentitum comprehensam pro.

No duis epicuri usu, ex vel delenit erroribus. Vis id diam interesset eloquentiam. Eum te eruditi mandamus, ut vix recusabo adolescens. Adhuc maluisset deterruisset vix te, ex vis viris nostro explicari.

# Bibliography {-}